### PR TITLE
Update tables for better use of API filters, context cancellation in list calls and page limiting for limit clause in query closes #42

### LINKED ISSUE #42: Update tables for better use of API filters, context cancellation in list calls and page limiting for limit clause in query
**Is your feature request related to a problem? Please describe.**

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from azuread_application where display_name = 'test-clusterSP-20190822160005' and app_id = '3c723985-7153-46e1-be37-c184dca79a9b';
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| display_name                  | id                                   | app_id                               | created_date_time         | is_authorization_service_enabled | oauth2_require_post_respons
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| test-clusterSP-20190822160005 | c2269df5-f119-4f1f-a5e9-7b09ea2f572c | 3c723985-7153-46e1-be37-c184dca79a9b | 2019-08-22T16:00:06+05:30 | false                            | false                      
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
> select * from azuread_application where display_name = 'test-clusterSP-20190822160005';
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| display_name                  | id                                   | app_id                               | created_date_time         | is_authorization_service_enabled | oauth2_require_post_respons
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
| test-clusterSP-20190822160005 | c2269df5-f119-4f1f-a5e9-7b09ea2f572c | 3c723985-7153-46e1-be37-c184dca79a9b | 2019-08-22T16:00:06+05:30 | false                            | false                      
+-------------------------------+--------------------------------------+--------------------------------------+---------------------------+----------------------------------+----------------------------
> select * from azuread_application limit 10;
+----------------------------------------------------------------------------------+--------------------------------------+--------------------------------------+---------------------------+------------
| display_name                                                                     | id                                   | app_id                               | created_date_time         | is_authoriz
+----------------------------------------------------------------------------------+--------------------------------------+--------------------------------------+---------------------------+------------
| testSubhajitSP-20200116153655                                                    | 2884abe0-40f0-4d47-8e9c-8a3623b46dfb | 5f46fd19-f98f-4df5-a71f-bedf760a57e4 | 2020-01-16T15:36:57+05:30 | false      
| testforcisSP-20191021200037                                                      | 155c6048-b9e3-4097-9f0d-f50dfe264a33 | 6a5633ae-38c9-45c2-a027-9625c8080438 | 2019-10-21T20:00:39+05:30 | false      
| Turbot Registration                                                              | 1edc0657-6828-4b43-8d4d-ada0d531ea47 | 435a8a3e-0e2e-45c1-a5aa-972f9595d1ed | 2020-10-06T09:16:51+05:30 | false      
| omero0623-Terraform 3-b21870ef-8d8e-4969-a625-7fb4795611c6                       | 08debdc7-f66c-4694-9c3c-47799d4f4631 | a8f8ea70-b34f-4f97-8000-4ce9803f3872 | 2020-06-23T16:05:58+05:30 | false      
| testtagsSP-20200224115309                                                        | 233977fe-9f72-4b08-92a2-c73db0e82ad6 | b85dd0be-9ec1-449e-8f88-6bca77c08a89 | 2020-02-24T11:53:13+05:30 | false      
| site-reco-mmn-asr-automationaccount_qTFX+asu23OKhBhqKiNmx8dUemt4oR5YkAzqo0nnQYQ= | 2d92cdc4-f139-448b-86a6-ebd4a76a3477 | 3f6d408c-a472-4293-8474-4301ed24bb16 | 2021-07-30T14:49:58+05:30 | false      
| TestImportDev                                                                    | 33437ba8-a54d-4ed2-9177-3a175ae58cfb | f7147c75-ba76-4e37-9709-e8e80f574020 | 2020-05-29T15:33:27+05:30 | false      
| Turbot Dev No Access                                                             | 2a25d066-f254-499a-9e71-14dfb6824156 | e9486b79-669d-417e-9368-264ebdb6f057 | 2019-07-10T18:49:13+05:30 | false      
| testSubhajitSP-20200124131852                                                    | 250decb7-81f0-4d2a-8338-214cb6d04459 | ef27bd2c-df2a-40f0-8a7a-1e4e6278b226 | 2020-01-24T13:18:55+05:30 | false      
| rup-testSP-20190822194017                                                        | 1c572fca-03e2-4c9c-a78d-9d0d5a362de0 | 4eb0f723-4771-4090-a8e4-3d16e867495c | 2019-08-22T19:40:17+05:30 | false      
+----------------------------------------------------------------------------------+--------------------------------------+--------------------------------------+---------------------------+------------

> select * from azuread_directory_role limit 10;
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------
| id                                   | description                                                                                                    | display_name              | role_template_id      
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------
| 849bf7bb-eb65-48ed-9dfa-39b6155e353c | Can read and manage compliance configuration and reports in Azure AD and Microsoft 365.                        | Compliance Administrator  | 17315797-102d-40b4-93e
| 72971a1d-dea5-42f7-b600-68270ce5e939 | Can read everything that a Global Administrator can, but not update anything.                                  | Global Reader             | f2ef992c-3afb-46b9-b7c
| eba14deb-0611-46fd-933e-aa29b4506145 | Security Administrator allows ability to read and manage security configuration and reports.                   | Security Administrator    | 194ae4cb-b126-40b2-bd5
| d9d9b915-2aef-4bca-862c-1d10c908a2e4 | Deprecated - Do Not Use.                                                                                       | Device Managers           | 2b499bcd-da44-4968-8ae
| 571dc422-4646-477f-b851-0b95a451bedc | Can read and write basic directory information. For granting access to applications, not intended for users.   | Directory Writers         | 9360feb5-f418-4baa-817
| 2e15cfcd-41e2-4019-a81c-d3fa8240fa47 | Can read basic directory information. Commonly used to grant directory read access to applications and guests. | Directory Readers         | 88d8e3e3-8f55-4a1e-953
| d7c0f498-df20-4efd-b1ca-33a8bb239047 | Can create and manage all aspects of app registrations and enterprise apps.                                    | Application Administrator | 9b895d92-2cd3-44c7-9d0
| efabd866-6be5-4ee8-af22-bf854b177920 | Can manage all aspects of users and groups, including resetting passwords for limited admins.                  | User Administrator        | fe930be7-5e62-47db-91a
| 1576ba81-b874-4f53-99ca-12ccfcc8f369 | Can perform common billing related tasks like updating payment information.                                    | Billing Administrator     | b0f54661-2d74-4c50-afa
| 8f98d949-be31-45fd-80b2-97db18304df5 | Can read security information and reports in Azure AD and Office 365.                                          | Security Reader           | 5d6b6bb7-de71-4623-b4a
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------
> select * from azuread_directory_role limit 100000;
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------
| id                                   | description                                                                                                    | display_name              | role_template_id      
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------
| 1576ba81-b874-4f53-99ca-12ccfcc8f369 | Can perform common billing related tasks like updating payment information.                                    | Billing Administrator     | b0f54661-2d74-4c50-afa
| eba14deb-0611-46fd-933e-aa29b4506145 | Security Administrator allows ability to read and manage security configuration and reports.                   | Security Administrator    | 194ae4cb-b126-40b2-bd5
| 72971a1d-dea5-42f7-b600-68270ce5e939 | Can read everything that a Global Administrator can, but not update anything.                                  | Global Reader             | f2ef992c-3afb-46b9-b7c
| 8f98d949-be31-45fd-80b2-97db18304df5 | Can read security information and reports in Azure AD and Office 365.                                          | Security Reader           | 5d6b6bb7-de71-4623-b4a
| 2e15cfcd-41e2-4019-a81c-d3fa8240fa47 | Can read basic directory information. Commonly used to grant directory read access to applications and guests. | Directory Readers         | 88d8e3e3-8f55-4a1e-953
| d7c0f498-df20-4efd-b1ca-33a8bb239047 | Can create and manage all aspects of app registrations and enterprise apps.                                    | Application Administrator | 9b895d92-2cd3-44c7-9d0
| 571dc422-4646-477f-b851-0b95a451bedc | Can read and write basic directory information. For granting access to applications, not intended for users.   | Directory Writers         | 9360feb5-f418-4baa-817
| f48b5c11-744d-42bf-8acc-57a665c600b4 | Can manage all aspects of Azure AD and Microsoft services that use Azure AD identities.                        | Global Administrator      | 62e90394-69f5-4237-919
| efabd866-6be5-4ee8-af22-bf854b177920 | Can manage all aspects of users and groups, including resetting passwords for limited admins.                  | User Administrator        | fe930be7-5e62-47db-91a
| d9d9b915-2aef-4bca-862c-1d10c908a2e4 | Deprecated - Do Not Use.                                                                                       | Device Managers           | 2b499bcd-da44-4968-8ae
| 849bf7bb-eb65-48ed-9dfa-39b6155e353c | Can read and manage compliance configuration and reports in Azure AD and Microsoft 365.                        | Compliance Administrator  | 17315797-102d-40b4-93e
+--------------------------------------+----------------------------------------------------------------------------------------------------------------+---------------------------+-----------------------

> select * from azuread_domain limit 0;
+----+---------------------+------------+------------------+------------+---------+-------------+--------------------+-------+-----------+
| id | authentication_type | is_default | is_admin_managed | is_initial | is_root | is_verified | supported_services | title | tenant_id |
+----+---------------------+------------+------------------+------------+---------+-------------+--------------------+-------+-----------+
+----+---------------------+------------+------------------+------------+---------+-------------+--------------------+-------+-----------+
> select * from azuread_domain limit 2;
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------
| id                       | authentication_type | is_default | is_admin_managed | is_initial | is_root | is_verified | supported_services                     | title                    | tenant_id       
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------
| turbotad.onmicrosoft.com | Managed             | true       | true             | true       | true    | true        | ["Email","OfficeCommunicationsOnline"] | turbotad.onmicrosoft.com | cdffd708-7da0-4c
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------
> select * from azuread_domain limit 10000;
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------
| id                       | authentication_type | is_default | is_admin_managed | is_initial | is_root | is_verified | supported_services                     | title                    | tenant_id       
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------
| turbotad.onmicrosoft.com | Managed             | true       | true             | true       | true    | true        | ["Email","OfficeCommunicationsOnline"] | turbotad.onmicrosoft.com | cdffd708-7da0-4c
+--------------------------+---------------------+------------+------------------+------------+---------+-------------+----------------------------------------+--------------------------+-----------------

> select * from azuread_service_principal limit 19
+--------------------------------------+----------------------------------------+-----------------+------------------------------------+--------------------------------------+-----------------------------
| id                                   | display_name                           | account_enabled | app_display_name                   | app_owner_organization_id            | app_role_assignment_required
+--------------------------------------+----------------------------------------+-----------------+------------------------------------+--------------------------------------+-----------------------------
| 0263705a-ad36-49c0-aeb2-f17ff35bd94f | Skype Teams Firehose                   | true            | Skype Teams Firehose               | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 021c8200-fd93-40d3-ae25-8203edd5d92f | testforcisSP-20191021200037            | true            | testforcisSP-20191021200037        | cdffd708-7da0-4cea-abeb-0a4c334d7f64 | false                       
| 060e7ca3-3958-4f8b-9f1b-13ab300b5a3a | f231dcd7119d4bc29c6297e8               | true            | <null>                             | <null>                               | false                       
| 042e56d9-4f47-4284-a867-e663074bcbc3 | cd7da8ebf7f44cb9b112653b               | true            | <null>                             | <null>                               | false                       
| 01646ec1-87ff-4ed6-8075-5c47d5524c5e | AzureDnsFrontendApp                    | true            | AzureDnsFrontendApp                | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 00302c5d-404a-41cf-9d3f-51e979b09307 | Yammer                                 | true            | Yammer                             | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 0401b4e1-c428-4922-9f5b-354c82c6375e | Azure Graph                            | true            | Azure Graph                        | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 001c0cf8-5de0-4956-ac9e-0536c253091b | IC3 Gateway                            | true            | IC3 Gateway                        | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 00ab90c8-f6a5-475e-ac08-fcca651e5a07 | Request Approvals Read Platform        | true            | Request Approvals Read Platform    | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 0122fea3-0e08-4a70-95fb-c879bb534f57 | M365DataAtRestEncryption               | true            | M365DataAtRestEncryption           | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
|                                      |                                        |                 |                                    |                                      |                             
| 03b10ab3-1309-410c-bf5c-7f2cb3bb4bda | Skype for Business Online              | true            | Skype for Business Online          | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
|                                      |                                        |                 |                                    |                                      |                             
|                                      |                                        |                 |                                    |                                      |                             
| 0347d95a-e059-4a06-891e-9c3785f14bdd | 206b549fdd504f2b9f1daab7               | true            | <null>                             | <null>                               | false                       
| 0472a4f6-322d-4376-b7d3-f1c3c5e559c1 | Bot Service Resource Provider          | true            | Bot Service Resource Provider      | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 03971c4c-f7c6-47e8-8df6-2c0286078c80 | Microsoft Intune Service Discovery     | true            | Microsoft Intune Service Discovery | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 00261fe6-7aa0-435a-be52-9eef29712ad6 | Microsoft Teams Bots                   | true            | Microsoft Teams Bots               | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
|                                      |                                        |                 |                                    |                                      |                             
| 060c9b48-4965-4f2a-9e55-0f30ca529194 | Skype Business Voice Directory         | true            | Skype Business Voice Directory     | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 0287f48a-fa54-49c0-b7a2-22b90a7a6fd9 | Azure HDInsight Surrogate Service      | true            | Azure HDInsight Surrogate Service  | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 02b01332-5f3f-40e7-9c81-1cc2017708ab | Teams Calling Meeting Devices Services | true            | Teams CMD Services Webinars        | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                       
| 038719b9-8df2-444e-aa4b-70f7922a3cc2 | testcisv85SP-20191017164927            | true            | testcisv85SP-20191017164927        | cdffd708-7da0-4cea-abeb-0a4c334d7f64 | false                       
+--------------------------------------+----------------------------------------+-----------------+------------------------------------+--------------------------------------+-----------------------------
> select * from azuread_service_principal where display_name = 'Skype Teams Firehose'
+--------------------------------------+----------------------+-----------------+----------------------+--------------------------------------+------------------------------+------------------------+-----
| id                                   | display_name         | account_enabled | app_display_name     | app_owner_organization_id            | app_role_assignment_required | service_principal_type | sign
+--------------------------------------+----------------------+-----------------+----------------------+--------------------------------------+------------------------------+------------------------+-----
| 0263705a-ad36-49c0-aeb2-f17ff35bd94f | Skype Teams Firehose | true            | Skype Teams Firehose | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                        | Application            | Azur
+--------------------------------------+----------------------+-----------------+----------------------+--------------------------------------+------------------------------+------------------------+-----
> select * from azuread_service_principal where service_principal_type = 'Application' limit 2
+--------------------------------------+--------------------------------+-----------------+--------------------------------+--------------------------------------+------------------------------+----------
| id                                   | display_name                   | account_enabled | app_display_name               | app_owner_organization_id            | app_role_assignment_required | service_p
+--------------------------------------+--------------------------------+-----------------+--------------------------------+--------------------------------------+------------------------------+----------
| 8195d20b-e5da-43e6-a314-88e77b3d541a | Microsoft App Access Panel     | true            | Microsoft App Access Panel     | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                        | Applicati
| f15d2401-babf-4c42-9abd-ef416d01368c | Windows Azure Active Directory | true            | Windows Azure Active Directory | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                        | Applicati
|                                      |                                |                 |                                |                                      |                              |          
|                                      |                                |                 |                                |                                      |                              |          
|                                      |                                |                 |                                |                                      |                              |          
|                                      |                                |                 |                                |                                      |                              |          
|                                      |                                |                 |                                |                                      |                              |          
+--------------------------------------+--------------------------------+-----------------+--------------------------------+--------------------------------------+------------------------------+----------
> select * from azuread_service_principal where not account_enabled
+--------------------------------------+---------------------------------------+-----------------+---------------------------------------+--------------------------------------+---------------------------
| id                                   | display_name                          | account_enabled | app_display_name                      | app_owner_organization_id            | app_role_assignment_requir
+--------------------------------------+---------------------------------------+-----------------+---------------------------------------+--------------------------------------+---------------------------
| 4d0d2677-3231-4815-abec-a3bad92c90bf | Microsoft Cloud App Security          | false           | Microsoft Cloud App Security          | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                     
|                                      |                                       |                 |                                       |                                      |                           
|                                      |                                       |                 |                                       |                                      |                           
| 8194a24e-b339-4188-8beb-9f66ffdcc531 | Microsoft To-Do                       | false           | Microsoft To-Do                       | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                     
| aae42adb-7d1b-4e39-b30a-043efe0648a7 | AADPremiumService                     | false           | AADPremiumService                     | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                     
| 17602be0-7b9a-4c82-8584-2b83e2e954a7 | Internal_AccessScope                  | false           | Internal_AccessScope                  | 0d2db716-b331-4d7b-aa37-7f1ac9d35dae | false                     
| 8cf57c4b-bc52-469b-baf3-e9f65c8e2732 | AzureLockbox                          | false           | AzureLockbox                          | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                     
| cc116d52-8527-42bf-8a21-384cff7b77b7 | Verifiable Credentials Issuer Service | false           | Verifiable Credentials Issuer Service | f8cdef31-a31e-4b4a-93e4-5f571e91255a | false                     
+--------------------------------------+---------------------------------------+-----------------+---------------------------------------+--------------------------------------+---------------------------

```
</details>

### CODE REVIEW

**Comment by spampell** [comment]
Hello, any idea when this might get merged?

**Comment by rajlearner17** [comment]
@spampell Thanks for following this out. We are at most releasing this by early next week.

**Comment by spampell** [comment]
Hello again. Just wanted to see if I could help with this at all. We'd like to start using this enhancement in our Steampipe stack.

**Review by bigdatasourav — APPROVED** [review]
LGTM

**Comment by bigdatasourav** [comment]
@spampell We have released this one. Please do check out and share your feedback with us.

**Pull request merged**
