### PR TITLE
Support querying appRoleAssignments

### PR DESCRIPTION
**Pull request by laurensknoll**
This change adds support for querying [appRoleAssignments](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0): Assignments recording that a user, group, or service principal is assigned an app role for an app.

Because the appRoleAssignments are accessible via multiple entry points, the following tables are added:
- azuread_group_app_role_assignment - App role assignments granted to group
- azuread_user_app_role_assignment - App role assignments granted to user
- azuread_service_principal_app_role_assignment - App role assignments granted to service principal
- azuread_application_app_role_assigned_to - App roles assigned to principals for a specific application
- azuread_service_principal_app_role_assigned_to - App roles assigned to principals for a specific service principal (enterprise application)

> Note that the app_role_assigned_to endpoints where not available in the used graph sdk version, therefore the package is updated to the latest version, causing changes in additional files.

# Example queries

I've included a couple example queries, if needed, I can add more.

## azuread_user_app_role_assignment get
```
select *
from azuread_user_app_role_assignment
where id = 'E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c'
  and user_id = '52504813-397e-411f-9149-e87b7605b3a5'
```

```
[
 {
  "_ctx": {
   "connection_name": "azuread",
   "steampipe": {
    "sdk_version": "5.8.0"
   }
  },
  "app_role_id": "9e79c739-f165-49e8-8745-fe08f1634b3b",
  "created_date_time": "2024-03-06T16:29:47+01:00",
  "deleted_date_time": null,
  "id": "E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c",
  "principal_display_name": "..",
  "principal_id": "52504813-397e-411f-9149-e87b7605b3a5",
  "principal_type": "User",
  "resource_display_name": "Google Cloud / G Suite Connector by Microsoft",
  "resource_id": "13e1f26a-d4fe-4b81-b23e-a39a454f3d17",
  "tenant_id": "c4c0a0f9-1600-4834-a577-30c7ef8a2228",
  "user_id": "52504813-397e-411f-9149-e87b7605b3a5"
 }
]
```

## azuread_user_app_role_assignment list
```
select *
from azuread_user_app_role_assignment
where user_id = '52504813-397e-411f-9149-e87b7605b3a5'
```

```
[
 {
  "_ctx": {
   "connection_name": "azuread",
   "steampipe": {
    "sdk_version": "5.8.0"
   }
  },
  "app_role_id": "9e79c739-f165-49e8-8745-fe08f1634b3b",
  "created_date_time": "2024-03-06T16:29:47+01:00",
  "deleted_date_time": null,
  "id": "E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c",
  "principal_display_name": "...",
  "principal_id": "52504813-397e-411f-9149-e87b7605b3a5",
  "principal_type": "User",
  "resource_display_name": "Google Cloud / G Suite Connector by Microsoft",
  "resource_id": "13e1f26a-d4fe-4b81-b23e-a39a454f3d17",
  "tenant_id": "c4c0a0f9-1600-4834-a577-30c7ef8a2228",
  "user_id": "52504813-397e-411f-9149-e87b7605b3a5"
 }
]
```

## azuread_application_app_role_assigned_to get
```
select *
from azuread_application_app_role_assigned_to
where id = 'E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c'
  and app_id = 'b724df63-9946-41a9-8bd0-a524c81dbf2c'
```

```
[
 {
  "_ctx": {
   "connection_name": "azuread",
   "steampipe": {
    "sdk_version": "5.8.0"
   }
  },
  "app_id": "b724df63-9946-41a9-8bd0-a524c81dbf2c",
  "app_role_id": "9e79c739-f165-49e8-8745-fe08f1634b3b",
  "created_date_time": "2024-03-06T16:29:47+01:00",
  "deleted_date_time": null,
  "id": "E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c",
  "principal_display_name": "..",
  "principal_id": "52504813-397e-411f-9149-e87b7605b3a5",
  "principal_type": "User",
  "resource_display_name": "Google Cloud / G Suite Connector by Microsoft",
  "resource_id": "13e1f26a-d4fe-4b81-b23e-a39a454f3d17",
  "tenant_id": "c4c0a0f9-1600-4834-a577-30c7ef8a2228"
 }
]
```

## azuread_application_app_role_assigned_to list 
```
select *
from azuread_application_app_role_assigned_to arat
where app_id = 'b724df63-9946-41a9-8bd0-a524c81dbf2c'
```

```
[
 {
  "_ctx": {
   "connection_name": "azuread",
   "steampipe": {
    "sdk_version": "5.8.0"
   }
  },
  "app_id": "b724df63-9946-41a9-8bd0-a524c81dbf2c",
  "app_role_id": "9e79c739-f165-49e8-8745-fe08f1634b3b",
  "created_date_time": "2024-03-06T16:29:47+01:00",
  "deleted_date_time": null,
  "id": "E0hQUn45H0GRSeh7dgWzpXedJZbRURRFjtFVb556x7c",
  "principal_display_name": "...",
  "principal_id": "52504813-397e-411f-9149-e87b7605b3a5",
  "principal_type": "User",
  "resource_display_name": "Google Cloud / G Suite Connector by Microsoft",
  "resource_id": "13e1f26a-d4fe-4b81-b23e-a39a454f3d17",
  "tenant_id": "c4c0a0f9-1600-4834-a577-30c7ef8a2228"
 }
]
```

### CODE REVIEW

**Comment by laurensknoll** [comment]
@misraved , @madhushreeray30 Could you review this PR?

**Comment by misraved** [comment]
Great to see the PR @laurensknoll 🎉 !!

Thank you so much for the contribution 👍.

**Comment by misraved** [comment]
@laurensknoll the changes look good 👍!!

Few questions before we move forward with the PR:
- Do the updated SDK dependencies have any effect on the pre-existing tables?
- From the SDK CHANGELOG, it is important to note the following points:
  - Has the authentication mechanism changed?
  - Has any column/response parameter been removed?
  - Has the datatype of any column changed?

**Comment by laurensknoll** [comment]
> @laurensknoll the changes look good 👍!!
> 
> Few questions before we move forward with the PR:
> 
> * Do the updated SDK dependencies have any effect on the pre-existing tables?
> * From the SDK CHANGELOG, it is important to note the following points:
>   
>   * Has the authentication mechanism changed?
>   * Has any column/response parameter been removed?
>   * Has the datatype of any column changed?

Happy to hear that @misraved . The SDK update did not affect the authentication mechanism, remove/rename columns or change data types.

PS. It would be useful to support a unit test to verify that with stub data or by supporting a `transform.FromModel[model](func(m) { return m.GetId() })`-kind of method to guard this changes. Do you know if anything like that is planned?

**Comment by misraved** [comment]
@laurensknoll thank you for the answers 👍.

Apologies, but we do not have a strong unit test to verify the changes. 

Could you please explain the usage of `transform.FromModel[model](func(m) { return m.GetId() })` in more detail? We could consider integrating it into our plugin and would like to understand its functionality and potential benefits better.

**Comment by laurensknoll** [comment]
> @laurensknoll thank you for the answers 👍.
> 
> Apologies, but we do not have a strong unit test to verify the changes.
> 
> Could you please explain the usage of `transform.FromModel[model](func(m) { return m.GetId() })` in more detail? We could consider integrating it into our plugin and would like to understand its functionality and potential benefits better.

Hi @misraved , 

Sure, the `transform.FromModel` takes a function instead of a string. This allows you to pass the interface method as `ADUserInfo.GetId`. As a result, the method reference is checked at compile-time.

Example table definition:

```go
func tableAzureAdUser(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "azuread_user",
		...
		Columns: []*plugin.Column{
			{Name: "display_name", Transform: FromModel(ADUserInfo.GetDisplayName)},
			{Name: "id", Transform: FromModel(ADUserInfo.GetId)},
			{Name: "user_principal_name", Transform: FromModel(ADUserInfo.GetUserPrincipalName)},
                         ...
		},
	}
}
``` 

Example FromModel implementation:

```go
func FromModel[V interface{}, R interface{}](f func(obj V) R) *transform.ColumnTransforms {
	fun := func(_ context.Context, d *transform.TransformData) (interface{}, error) {
		item := d.HydrateItem.(*V)
		if item == nil {
			return nil, fmt.Errorf("failed to cast hyradeItem %T to model %T", d.HydrateItem, *new(V))
		}

		return f(*item), nil
	}

	return transform.From(fun)
}
```

**Comment by misraved** [comment]
Thanks @laurensknoll for the insight 👍!!

**Comment by misraved** [comment]
Apologies for the delay on this PR @laurensknoll

I have tested the changes and they look good. Could you please resolve the merge conflicts in the PR so that we can proceed with the release?

Thanks!!

**Comment by laurensknoll** [comment]
> Apologies for the delay on this PR @laurensknoll
> 
> I have tested the changes and they look good. Could you please resolve the merge conflicts in the PR so that we can proceed with the release?
> 
> Thanks!!



> Apologies for the delay on this PR @laurensknoll
> 
> I have tested the changes and they look good. Could you please resolve the merge conflicts in the PR so that we can proceed with the release?
> 
> Thanks!!



> Apologies for the delay on this PR @laurensknoll
> 
> I have tested the changes and they look good. Could you please resolve the merge conflicts in the PR so that we can proceed with the release?
> 
> Thanks!!

Thanks for the update @misraved . I've resolved the merge conflicts such that you can proceed with a final review.

**Review by misraved — APPROVED** [review]

**Pull request merged**
