### PR TITLE
azuread_directory_role - error (SQLSTATE HV000) Closes #114

### LINKED ISSUE #114: azuread_directory_role - error (SQLSTATE HV000)
When trying to run the following query: https://hub.steampipe.io/plugins/turbot/azuread/tables/azuread_directory_role#list-users-with-access-to-directory-roles
The following error is returned: table 'azuread_directory_role' column 'member_ids' requires hydrate data from getDirectoryRoleMembers, which failed with error null. (SQLSTATE HV000)

However when i run the query: "select * from azuread_directory_role limit 1" i do get a result. 
This returns the Azure Information Protection Administrator as display_name

Increasing the limit will return the same error. 
I can execute queries on all tables except the azuread_directory_role because it returns this error.

### PR DESCRIPTION
**Pull request by ParthaI**
# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

**Comment by hannewijkBDO** [comment]
steampipe query 'select * from azuread_directory_role'

Error: table 'azuread_directory_role' column 'member_ids' requires hydrate data from getDirectoryRoleMembers, which failed with error null.
 (SQLSTATE HV000)

+----+-------------+--------------+------------------+------------+-------+-----------+------+
| id | description | display_name | role_template_id | member_ids | title | tenant_id | _ctx |
+----+-------------+--------------+------------------+------------+-------+-----------+------+
+----+-------------+--------------+------------------+------------+-------+-----------+------+


steampipe query 'select * from azuread_directory_role limit 1'
+--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+
| id                                   | description                                                                                   | display_name                 | role_template_id                     | member_ids | title                        | tenant_id                            | _ctx                          |
+--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+
| <id> | Can see only tenant level aggregates in Microsoft 365 Usage Analytics and Productivity Score. | Usage Summary Reports Reader | <role-template-id> | []         | Usage Summary Reports Reader | <tenant_id> | {"connection_name":"azuread"} |
+--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+

Hopefully is this information sufficient. I should note that the user permission are "Global Reader".

**Comment by ParthaI** [comment]
> steampipe query 'select * from azuread_directory_role'
> 
> Error: table 'azuread_directory_role' column 'member_ids' requires hydrate data from getDirectoryRoleMembers, which failed with error {"Code":"","Message":"AzureCLICredential: signal: killed"}. (SQLSTATE HV000)
> 
> +----+-------------+--------------+------------------+------------+-------+-----------+------+ | id | description | display_name | role_template_id | member_ids | title | tenant_id | _ctx | +----+-------------+--------------+------------------+------------+-------+-----------+------+ +----+-------------+--------------+------------------+------------+-------+-----------+------+
> 
> steampipe query 'select * from azuread_directory_role limit 1' +--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+ | id | description | display_name | role_template_id | member_ids | title | tenant_id | _ctx | +--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+ | | Can see only tenant level aggregates in Microsoft 365 Usage Analytics and Productivity Score. | Usage Summary Reports Reader | | [] | Usage Summary Reports Reader | <tenant_id> | {"connection_name":"azuread"} | +--------------------------------------+-----------------------------------------------------------------------------------------------+------------------------------+--------------------------------------+------------+------------------------------+--------------------------------------+-------------------------------+
> 
> Hopefully is this information sufficient. I should note that the user permission which are used to run the queries are "Global Reader".

Hi @hannewijkBDO ,
Thank you for the information. It is encouraging to see that we now receive error messages instead of null values.

As you mentioned, we attempted to reproduce the error on our side by assigning different levels of permissions and exclusively GlobalReaders.

However, we are still not able to reproduce the error. We can still get the result with & without the limit.

```
> select * from azuread_directory_role
+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+--------------------------------------+----------->
| id                                   | description                                                                                                                                | display_name                        | role_template_id                     | member_ids>
+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+--------------------------------------+----------->
| 3aed8c5a-8882-49da-8578-45373ff18cb8 | Allowed to view, set and reset authentication method information for any non-admin user.                                                   | Authentication Administrator        | c4e39bd9-1100-46d3-8c65-fb160da0071f | []        >
| 849bf7bb-eb65-48ed-9dfa-39b6155e353c | Can read and manage compliance configuration and reports in Azure AD and Microsoft 365.                                                    | Compliance Administrator            | 17315797-102d-40b4-93e0-432062caca18 | []        >
| 1576ba81-b874-4f53-99ca-12ccfcc8f369 | Can perform common billing related tasks like updating payment information.                                                                | Billing Administrator               | b0f54661-2d74-4c50-afa3-1ec803f12efe | ["ac26c9c6>
| b9937625-4e6b-409f-84ac-33a3b8754ecd | Can read sign-in and audit reports.                                                                                                        | Reports Reader                      | 4a5d8f65-41da-4de4-8968-e035b65339cf | ["15518ed6>
| 8f98d949-be31-45fd-80b2-97db18304df5 | Can read security information and reports in Azure AD and Office 365.                                                                      | Security Reader                     | 5d6b6bb7-de71-4623-b4af-96380a352509 | ["15518ed6>
| 72971a1d-dea5-42f7-b600-68270ce5e939 | Can read everything that a Global Administrator can, but not update anything.                                                              | Global Reader                       | f2ef992c-3afb-46b9-b7cf-a126ee74c451 | ["06fd46b0>
| efabd866-6be5-4ee8-af22-bf854b177920 | Can manage all aspects of users and groups, including resetting passwords for limited admins.                                              | User Administrator                  | fe930be7-5e62-47db-91af-98c3a49a38b1 | ["2f617226>
| fba1cf3f-e06d-48a8-9269-cf477d28abfa | Can create and manage the authentication methods policy, tenant-wide MFA settings, password protection policy, and verifiable credentials. | Authentication Policy Administrator | 0526716b-113d-4c15-b2c8-68e3c22b9f80 | []        >
| d9d9b915-2aef-4bca-862c-1d10c908a2e4 | Deprecated - Do Not Use.                                                                                                                   | Device Managers                     | 2b499bcd-da44-4968-8aec-78e1674fa64d | ["0845b201>
| 571dc422-4646-477f-b851-0b95a451bedc | Can read and write basic directory information. For granting access to applications, not intended for users.                               | Directory Writers                   | 9360feb5-f418-4baa-8175-e2a00bac4301 | ["0845b201>
| d7c0f498-df20-4efd-b1ca-33a8bb239047 | Can create and manage all aspects of app registrations and enterprise apps.                                                                | Application Administrator           | 9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3 | ["2f617226>
| 38fd1c77-cf7b-42ce-b96c-3e61ff8516ae | Can manage Conditional Access capabilities.                                                                                                | Conditional Access Administrator    | b1be1c3e-b65d-4f19-8427-f6fa0d97feb9 | ["92f0bf94>
| 2e15cfcd-41e2-4019-a81c-d3fa8240fa47 | Can read basic directory information. Commonly used to grant directory read access to applications and guests.                             | Directory Readers                   | 88d8e3e3-8f55-4a1e-953a-9b9898b8876b | ["0fb1aa5d>
| f48b5c11-744d-42bf-8acc-57a665c600b4 | Can manage all aspects of Azure AD and Microsoft services that use Azure AD identities.                                                    | Global Administrator                | 62e90394-69f5-4237-9190-012177145e10 | ["08e2448b>
| eba14deb-0611-46fd-933e-aa29b4506145 | Security Administrator allows ability to read and manage security configuration and reports.                                               | Security Administrator              | 194ae4cb-b126-40b2-bd5b-6091b380977d | ["98d2628a>
| 23de5799-d17c-456d-b3a1-ad806ebb7221 | Can create application registrations independent of the 'Users can register applications' setting.                                         | Application Developer               | cf1c38e5-3621-4004-a7cb-879624dced7c | ["92f0bf94>
+--------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------+--------------------------------------+----------->

```

```
> select * from azuread_directory_role limit 1
+--------------------------------------+-----------------------------------------------------------------------------+-----------------------+--------------------------------------+------------------------------------------+-----------------------+--------------------->
| id                                   | description                                                                 | display_name          | role_template_id                     | member_ids                               | title                 | tenant_id           >
+--------------------------------------+-----------------------------------------------------------------------------+-----------------------+--------------------------------------+------------------------------------------+-----------------------+--------------------->
| 1576ba81-b874-4f53-99ca-12ccfcc8f369 | Can perform common billing related tasks like updating payment information. | Billing Administrator | b0f54661-2d74-4c50-afa3-1ec803f12efe | ["ac26c9c6-4243-4da4-bf84-7ef3e9e9e4f2"] | Billing Administrator | cdffd708-7da0-4cea-a>
+--------------------------------------+-----------------------------------------------------------------------------+-----------------------+--------------------------------------+------------------------------------------+-----------------------+--------------------->

```

We would appreciate it if you could let us know the following

- Which authentication mode are you using, such as AzureCLI Based authentication, client secret authentication or anything else as per mentioned in [doc](https://github.com/turbot/steampipe-plugin-azuread/blob/main/config/azuread.spc) ?
- Additionally, could you please share your `~/.steampipe/config/azuread.spc` file with us (ensuring that any sensitive information is removed)?
- In our case, we tested the above scenarios with Azure CLI-based Authentication. Could you please give it a try?

This will help us to match your settings at our end to be able to reproduce.

Thank You!

**Comment by hannewijkBDO** [comment]
Hi @ParthaI,
To authenticate to azure, i have used the AzureCLI - devicecode flow to login (az login --device-code). 
Nothing is changed in the config file as you can see below: 

cat ~/.steampipe/config/azuread.spc
connection "azuread" {
  plugin = "azuread"

  # Defaults to "AZUREPUBLICCLOUD". Valid environments are "AZUREPUBLICCLOUD", "AZURECHINACLOUD" and "AZUREUSGOVERNMENTCLOUD"
  # environment = "AZUREPUBLICCLOUD"

  # You can connect to Azure using one of options below:

  # Use client secret authentication (https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-2-create-a-new-application-secret)
  # tenant_id     = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  # client_id     = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"
  # client_secret = "ZZZZZZZZZZZZZZZZZZZZZZZZ"

  # Use client certificate authentication (https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-1-upload-a-certificate)
  # required options:
  # tenant_id             = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  # client_id             = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"
  # certificate_path      = "~/home/azure_cert.pem"
  # certificate_password  = "notreal~pwd"

  # Use a managed identity (https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)
  # This method is useful with Azure virtual machines
  # tenant_id  = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  # client_id  = "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"
  # enable_msi = true
  # msi_endpoint = "http://169.254.169.254/metadata/identity/oauth2/token"

  # If no credentials are specified, the plugin will use Azure CLI authentication
}

**Comment by rajlearner17** [comment]
@hannewijkBDO Thanks for sharing the info for this exciting case; as @ParthaI is absent today, trying to get some more input here 

This is what we tried in brief,

- Specified `Global Reader` role in Azure AD level
- Specified `Reader` as one of the subscription levels, which is required to have. I hope this is assigned and it allows your `az login`
- We follow the same `az login ` CLI-based authentication.
- With a similar setting in the SPC file

We still need to replicate it. As the `select * from azuread_directory_role` works for me as well

**Would you mind providing a few more inputs, such as**

- Steampipe CLI version you are using, i.e. `steampipe -v` & azure-ad plugin version? (Apology if I missed it in any conversation)
- Are you also using the `Azure plugin` with the same tenant? Please query your subscription table and check if it works.
- Can you provide us with your assigned in subscription level permission in the same tenant?

- Does this query work?

```bash
select * from azuread_directory_role where display_name in ( 'Directory Writers', 'Authentication Administrator', 'Security Reader')
```

**Trying to validate your get call** 

```bash
 select * from azuread_directory_role where id in ('1576ba81-b874-4f53-99ca-12ccfcc8f369', '23de5799-d17c-456d-b3a1-ad806ebb7221', '72971a1d-dea5-42f7-b600-68270ce5e939') 
```

_Note that you can get these IDs using the Cloud-Shell terminal; the above Role IDs may be different for different tenants_

Use these two PS commands.
```
PS /home/abc> Connect-AzureAD  
PS /home/abc> Get-AzureADDirectoryRole
```
Sample screen attached,

image

Sorry for the inconvenience; we will check this and try our best to resolve it.

**Pull request closed without merging**
